version: "2.0"
services:
  nginx:
    build: ./nginx
    links:
      - api
      - frontend
    ports:
      - "80:80"
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "8080"
  api:
    build: ./api
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - "3000"
