version: "2.0"
services:
  frontend:
    build: ./frontend
    volumes:
      - ./frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 80:8080
    links:
      - api
  api:
    build: ./api
    volumes:
      - ./api:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - 3000:3000
